collections:
  posts:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "RedstoneTim"
      
plugins:
  - jekyll-optional-front-matter

markdown: kramdown